### ISSUE TITLE
Dust law improvements

### ISSUE THREAD

**Issue by stevet40** [RickKessler/SNANA#1432]
This is more a to-do/wishlist, following on from #1431. Over the past few months we've made some improvements to the dust laws implemented in SNANA. There are still some things that could be improved further, listed below:
- [ ] Re-visit the F99-like dust laws depending on the outcome of https://github.com/karllark/dust_extinction/issues/243.
- [x] Make sure all $R_V$ and $\lambda$ limits are enforced properly.
- [x] Possibly implement the second derivatives in the F99 function directly. Currently I have hardcoded some matrices to handle this. It was okay when it was just F99, but now there are three F99-like laws with slightly different arrangements of spline knots, things have really gotten out of hand.
- [x] Add the option to modify the $f_A$ parameter in the [Gordon et al. (2016](https://ui.adsabs.harvard.edu/abs/2016ApJ...826..104G/abstract) dust law. I'll need help from @RickKessler with this. Would also be useful to have input from @djbrout about what your intended use case was? (see also #1434)
- [x] Implement additional $R_V$-dependent extinction laws, to "complete the set" of curves from [`dust_extinction`](https://github.com/karllark/dust_extinction). Outstanding ones are listed below.
- [x] Document these things somewhere (done in #1433).

More dust laws to add:
- [x] [Maíz Apellániz et al. (2014)](https://ui.adsabs.harvard.edu/abs/2014A%26A...564A..63M/abstract): This uses a spline, but not quite the same type as F99 (as far as I can tell). They give IDL code in the paper, and an implementation is included in `dust_extinction`. Only optical and NIR (no UV).
- [x] [Fitzpatrick et al. (2019)](https://ui.adsabs.harvard.edu/abs/2019ApJ...886..108F/abstract): The implementation in `dust_extinction` is based on a B-spline (but that might just be another boundary conditions issue). The paper talks about cubic splines though, and based on past codes Fitzpatrick seems like a natural cubic kinda guy (a man after my own heart). In any case, TBC whether this will be easy or annoying (done in #1437 ).
- [x] [Goobar (2008)](https://ui.adsabs.harvard.edu/abs/2008ApJ...686L.103G/abstract): Power law for circumstellar dust.

**Comment by stevet40** [comment]
Cc @ado8, who is thinking about these things in a BayeSN context
